require('fullpage.js/dist/jquery.fullpage.js')
require('jquery-dropdown')
require('jquery-powertip')
require('jquery-minicolors')
require('jquery-validation')
require('js-cookie')
require('rome')
require('webpack-jquery-ui/sortable')
